.TH "/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/__init__.py" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/__init__.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBvalidator\fP"
.br
.RI "\fI\fBA set of scripts used to validate the outputs of the document classification cartridge\&.\fP \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
