.TH "/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/csvparser.py" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/csvparser.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvalidator\&.csvparser\&.Parser\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBvalidator\&.csvparser\fP"
.br
.ti -1c
.RI "\fBcsvparser\fP"
.br
.RI "\fI\fBScript used to parse the annotations csv files and compare between manual and Luxid annotations\&.\fP \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBvalidator\&.csvparser\&.main\fP"
.br
.RI "\fIModule entry point\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBvalidator\&.csvparser\&.SEP\fP = '|'"
.br
.ti -1c
.RI "string \fBvalidator\&.csvparser\&.END\fP = '\\n'"
.br
.ti -1c
.RI "string \fBvalidator\&.csvparser\&.DEFAULTMANUAL\fP = '1'"
.br
.ti -1c
.RI "string \fBvalidator\&.csvparser\&.DEFAULTCOMMON\fP = '1'"
.br
.ti -1c
.RI "string \fBvalidator\&.csvparser\&.DEFAULTTEMIS\fP = '0'"
.br
.ti -1c
.RI "int \fBvalidator\&.csvparser\&.MANUAL\fP = 0"
.br
.ti -1c
.RI "int \fBvalidator\&.csvparser\&.COMMON\fP = 1"
.br
.ti -1c
.RI "int \fBvalidator\&.csvparser\&.TEMISONLY\fP = 2"
.br
.ti -1c
.RI "\fBvalidator\&.csvparser\&.INCLUDEORGS\fP = False"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
