.TH "csvparser" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
csvparser \- 
.PP
\fBScript used to parse the annotations csv files and compare between manual and Luxid annotations\&.\fP  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBScript used to parse the annotations csv files and compare between manual and Luxid annotations\&.\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
