.TH "deprecated" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBMember \fBvalidator::extractor_deprecated\&.convert_classif_xml_to_csv\fP \fP" 1c
see temisxmlparser instead  
.IP "\fBMember \fBvalidator::extractor_deprecated\&.main\fP \fP" 1c
see temisxmlparser instead 
.PP

