.TH "/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/excelgenerator.py" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/excelgenerator.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvalidator\&.excelgenerator\&.ExcelGenerator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBvalidator\&.excelgenerator\fP"
.br
.ti -1c
.RI "\fBexcelgenerator\fP"
.br
.RI "\fI\fBScript used to generate excel files based on the results of comparison between manual and Luxid annotations\&.\fP \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBvalidator\&.excelgenerator\&.main\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
