.TH "excelgenerator" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
excelgenerator \- 
.PP
\fBScript used to generate excel files based on the results of comparison between manual and Luxid annotations\&.\fP  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBScript used to generate excel files based on the results of comparison between manual and Luxid annotations\&.\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
