.TH "/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/extractor_deprecated.py" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/extractor_deprecated.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBvalidator\&.extractor_deprecated\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBvalidator\&.extractor_deprecated\&.convert_classif_xml_to_csv\fP"
.br
.ti -1c
.RI "def \fBvalidator\&.extractor_deprecated\&.main\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
