.TH "/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/manualtagsimport.py" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/manualtagsimport.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBvalidator\&.manualtagsimport\fP"
.br
.ti -1c
.RI "\fBmanualtagsimport\fP"
.br
.RI "\fI\fBScript used to copy the csv files containing 'manual' annotations in the respective corpus folders for comparison with the cartridge\&.\fP \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBvalidator\&.manualtagsimport\&.copy_csvfile_to_corpus_folder\fP"
.br
.RI "\fICopies the annotation file to the corresponding corpus folder\&. \fP"
.ti -1c
.RI "def \fBvalidator\&.manualtagsimport\&.main\fP"
.br
.RI "\fIModule entry point\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
