.TH "manualtagsimport" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
manualtagsimport \- 
.PP
\fBScript used to copy the csv files containing 'manual' annotations in the respective corpus folders for comparison with the cartridge\&.\fP  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBScript used to copy the csv files containing 'manual' annotations in the respective corpus folders for comparison with the cartridge\&.\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
