.TH "temisxmlparser" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
temisxmlparser \- 
.PP
\fBScript used to extract classification annotations from the xml files produced by the Luxid workflow\&.\fP  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBScript used to extract classification annotations from the xml files produced by the Luxid workflow\&.\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
