.TH "/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/temisxmlparser.py" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/stephane/Documents/LiClipse Workspace/ClassifValidation/validator/temisxmlparser.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBvalidator\&.temisxmlparser\fP"
.br
.ti -1c
.RI "\fBtemisxmlparser\fP"
.br
.RI "\fI\fBScript used to extract classification annotations from the xml files produced by the Luxid workflow\&.\fP \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBvalidator\&.temisxmlparser\&.convert_classif_xml_to_csv\fP"
.br
.RI "\fI\fBRead the xml file, extract the file name and the annotations and append this information to the csv file of the corresponding corpus\&.\fP \fP"
.ti -1c
.RI "def \fBvalidator\&.temisxmlparser\&.main\fP"
.br
.RI "\fI\fBRuns the extraction of the classification's annotations\fP \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
