.TH "validator.extractor_deprecated" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
validator.extractor_deprecated \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBconvert_classif_xml_to_csv\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Created on Jul 18, 2014

@author: Stephane VARIN

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def validator\&.extractor_deprecated\&.convert_classif_xml_to_csv (xmlfile_folder, xmlfile)"

.PP
\fBDeprecated\fP
.RS 4
see temisxmlparser instead 
.RE
.PP
.PP
.nf
convert_classif_xml_to_csv:
.fi
.PP
 
.SS "def validator\&.extractor_deprecated\&.main ()"

.PP
\fBDeprecated\fP
.RS 4
see temisxmlparser instead 
.RE
.PP
.PP
.nf
main:
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
