.TH "validator.excelgenerator" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
validator.excelgenerator \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExcelGenerator\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def validator\&.excelgenerator\&.main ()"

.PP
.nf
main:

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
