.TH "validator" 3 "Fri Dec 5 2014" "ClassifValidation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
validator \- 
.PP
\fBA set of scripts used to validate the outputs of the document classification cartridge\&.\fP  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBcsvparser\fP"
.br
.ti -1c
.RI "\fBexcelgenerator\fP"
.br
.ti -1c
.RI "\fBextractor_deprecated\fP"
.br
.ti -1c
.RI "\fBmanualtagsimport\fP"
.br
.ti -1c
.RI "\fBtemisxmlparser\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA set of scripts used to validate the outputs of the document classification cartridge\&.\fP 

Starting with the xml files produced by a Luxid workflow to generate Excel files with color highlighting to identify differences between successive versions of the cartridge\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ClassifValidation from the source code\&.
